name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download Source file
      uses: actions/checkout@v2
      with:
        ref: blog-source

    - name: Prepare Node env
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"

    - name: Set Env
      env: 
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}  
      run: |
        git config --global user.name 'da0mao'
        git config --global user.email 'da0mao@hotmail.com'
        sed -i "s/ACCESS_TOKEN/$ACCESS_TOKEN/g" ./_config.yml

    - name: Hexo
      run: |
        git clone -b master https://github.com/da0mao/hexo-theme-next.git themes/next
        npm i -g hexo-cli
        npm install gulp -g
        npm i
        gulp